### ISSUE TITLE
Input-SDK for iOS upload

### ISSUE THREAD

**Issue by sklencar** [lutraconsulting/input-sdk#29]
Currently, its quite unclear how SDK is uploaded and shared on a dropbox. Uploaded SDK tar.gz file cannot be searched although it seems to be uploaded manually by a user through web.

**Comment by PeterPetrik** [comment]
it looks like the folder which is currectly used for uploading is a "private" folder of the dropbox app and only i can upload to it. for future we should create another folder that is "regular" and can be uploaded by everyone with permissions. I can do that change and let you know.

**Comment by PeterPetrik** [comment]
should be uploaded to https://www.dropbox.com/work/_Projects/input/input_sdks and shared for public link
