### ISSUE TITLE
Support WFS in input app (iOS and android both not working)

### ISSUE THREAD

**Issue by CharlotteEijkelenboom1** [lutraconsulting/input-sdk#44]
I want to add a WFS connection in the input app, I upload my WFS to QGIS and it works fine, but when I synchronize the project the WFS layer is not visible in the input app. Could you maybe help me with that?

**Comment by PeterPetrik** [comment]
duplicate of #36 . lets please discuss on the formerly opened ticket

**Comment by CharlotteEijkelenboom1** [comment]
This issue is about WFS on iOS, it's also not working on my android..

Op do 24 jun. 2021 om 14:21 schreef Peter Petrik ***@***.***>:
