### ISSUE TITLE
[DRIVER/FORMAT] support GeoPDF

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/input-sdk#48]
similarly to https://github.com/qgis/QGIS-Mac-Packager/issues/75

**Comment by PeterPetrik** [comment]
[Uploading VaziyetPlani Mobil.zip…]()

**Comment by saberraz** [comment]
I tried the zipped file in your previous comment.

**Comment by PeterPetrik** [comment]
this should be supported by input 1.3.0

**Comment by PeterPetrik** [comment]
[peter.petrik](https://public.cloudmergin.com/projects/peter.petrik)/[test-geopdf](https://public.cloudmergin.com/projects/peter.petrik/test-geopdf)
