### ISSUE TITLE
Support JPEG compression in GDAL

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input-sdk#60]
Currently we build GDAL without JPEG support, so even GeoTIFF files with JPEG compression can't be loaded in Input:

https://github.com/lutraconsulting/input-sdk/blob/master/android/recipes/gdal/recipe.sh#L67

**Comment by wonder-sk** [comment]
Actually this is a bug, because previously (before AAB updates) we didn't disable JPEG driver:
https://github.com/lutraconsulting/input-sdk/blob/2588d6c416ebf4d371d6702717c321cd7e36468b/android/recipes/gdal/recipe.sh#L51

**Comment by PeterPetrik** [comment]
https://github.com/OSGeo/gdal/commit/f3090267d5c30e4560df5cde7ee3c805a8a2ddab
