### ISSUE TITLE
Upgrade Qt to 5.13.x

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/input-sdk#9]
iOS only - with Qt 5.11.x we have issues with the display notch and the bar at the bottom on the newer phones - both seem to get fixed when Input is built with 5.13
- https://github.com/lutraconsulting/input/issues/476
- https://github.com/lutraconsulting/input/issues/513

**Comment by PeterPetrik** [comment]
will update directly to 5.14.1
